name: Executar Robo CashOut

on:
  schedule:
    # 11:00 UTC corresponde às 08:00 de Brasília
    - cron: '0 11 * * *'
  workflow_dispatch: # Permite que você rode manualmente pelo botão no GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pytz

      - name: Rodar Robo CachOut
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          X_RAPIDAPI_KEY: ${{ secrets.X_RAPIDAPI_KEY }}
        run: python cachout.py
