name: Atualizar Ranking Flashscore

on:
  push:
    paths:
      - 'ranking/ranking.py'
  schedule:
    # 03:05 UTC (00:05 AM Horário de Brasília)
    - cron: '5 3 * * *'
  workflow_dispatch: # Permite rodar manual quando você quiser testar os logs

jobs:
  run-ranking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb

      - name: Instalar Dependências Python
        run: |
          pip install undetected-chromedriver selenium requests webdriver-manager Pillow pytesseract

      - name: Executar Script de Ranking
        run: |
          xvfb-run python ranking/ranking.py

      - name: Commit e Push das atualizações
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          # Adiciona especificamente a pasta ranking
          git add ranking/ranking_db.json ranking/pendentes.json || true
          git commit -m "Ranking atualizado: $(date +'%d/%m/%Y %H:%M')" || echo "Sem mudanças"
          git push
        
