name: Robo de Apostas Diário

on:
  schedule:
    # 11:00 UTC é 08:00 Horário de Brasília
    # 17:00 UTC é 14:00 Horário de Brasília
    - cron: '0 11,17 * * *'
  workflow_dispatch: # Permite que você rode manualmente se quiser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install requests

      - name: Executar Robô
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
        
