name: Execucao Diario Bot Apostas

on:
  push:
    paths:
      - 'main.py'
  schedule:
    # 07:00 Horário de Brasília = 10:00 UTC
    - cron: '00 10 * * *'
  workflow_dispatch: # Permite rodar manualmente pelo celular se precisar

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Executar bot Selenium
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
        
