name: _Teste main bot de aposta

on:
  push:
    paths:
      - 'testes/teste_main.py'
      - 'testes/**'
  workflow_dispatch:

jobs:
  run-test-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: 1. Executar bot de Teste
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          # Adiciona o diretório raiz ao PYTHONPATH para que os imports funcionem
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python testes/teste_main.py
          
