name: Teste Isolado de Links Google-Betano

on:
  workflow_dispatch: # Permite rodar manualmente pelo botão "Run workflow"
  push:
    paths:
      - 'testes/teste_links.py' # Roda se você editar o arquivo de teste
      - '.github/workflows/teste_links.yml' # Roda se você editar este yml

jobs:
  run-test-google:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install undetected-chromedriver selenium

      - name: Executar Teste de Link (Pasta Testes)
        env:
          # Define o diretório raiz como caminho de busca para o Python
          PYTHONPATH: ${{ github.workspace }}
        run: python testes/teste_links.py
        
